// <auto-generated />
using System;
using CarParkManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarParkManagement.Migrations
{
    [DbContext(typeof(ParkingSpaceDbContext))]
    [Migration("20260121121503_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarParkManagement.Models.ParkingSpace", b =>
                {
                    b.Property<int>("SpaceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceNumber"));

                    b.Property<string>("ParkedVehicleVehicleReg")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ParkingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SpaceNumber");

                    b.HasIndex("ParkedVehicleVehicleReg");

                    b.ToTable("ParkedVehicles");
                });

            modelBuilder.Entity("CarParkManagement.Models.Vehicle", b =>
                {
                    b.Property<string>("VehicleReg")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("VehicleReg");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("CarParkManagement.Models.ParkingSpace", b =>
                {
                    b.HasOne("CarParkManagement.Models.Vehicle", "ParkedVehicle")
                        .WithMany()
                        .HasForeignKey("ParkedVehicleVehicleReg");

                    b.Navigation("ParkedVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
